import { Inter } from "next/font/google";
import { LanguageProvider } from "../../context/LanguageContext";
import { TranslationProvider } from "../../context/TranslationContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LanguageProvider>
          <TranslationProvider>{children}</TranslationProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
